### PR TITLE
Add ECMAScript 6 Modules test cases

### PR DESCRIPTION
**Pull request by AtOMiCNebula**
Microsoft Edge's current set of tests for an ECMAScript6 Modules implementation via the script element (<script type="module">).

### CODE REVIEW

**Comment by AtOMiCNebula** [comment]
@travisleithead @arronei @thejohnjansen

**Comment by AtOMiCNebula** [comment]
@thejohnjansen poke

**Comment by AtOMiCNebula** [comment]
There are four core testharness files in this review (crossorigin.html, errorhandling.html, execorder.html, and imports.html) which pull in the others.  The inner ones to not use testharness.js directly, since I didn't think it was useful to have testharness.js running tests in contained iframes that also ran testharness.js.  These tests run in iframes to isolate themselves from each other.  I can move these subtests into a "support" directory, to make that more clear.

- [ ] Move subtests into a support directory
- [ ] Meta tags

**Comment by thejohnjansen** [comment]
What I mean by that thumbs up, is LEAVE IT AS IS. I like this, actually. I'm going to merge it. Thanks for clarifying.

**Pull request merged**
